DATA PREPROCESSING

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset= pd.read_csv('Titanic-Dataset.csv')
dataset.head(),dataset.shape

(   PassengerId  Survived  Pclass  \
 0            1         0       3   
 1            2         1       1   
 2            3         1       3   
 3            4         1       1   
 4            5         0       3   
 
                                                 Name     Sex   Age  SibSp  \
 0                            Braund, Mr. Owen Harris    male  22.0      1   
 1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
 2                             Heikkinen, Miss. Laina  female  26.0      0   
 3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
 4                           Allen, Mr. William Henry    male  35.0      0   
 
    Parch            Ticket     Fare Cabin Embarked  
 0      0         A/5 21171   7.2500   NaN        S  
 1      0          PC 17599  71.2833   C85        C  
 2      0  STON/O2. 3101282   7.9250   NaN        S  
 3      0            113803  53.1000  C123        S  
 4      0            373450   8.0500

In [3]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
dataset.drop(dataset.columns[[3,8,10]],axis=1,inplace=True)

In [5]:
dataset.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [6]:
x=dataset.iloc[:,2:9].values
y=dataset.iloc[:,1].values

In [7]:
print(x)

[[3 'male' 22.0 ... 0 7.25 'S']
 [1 'female' 38.0 ... 0 71.2833 'C']
 [3 'female' 26.0 ... 0 7.925 'S']
 ...
 [3 'female' nan ... 2 23.45 'S']
 [1 'male' 26.0 ... 0 30.0 'C']
 [3 'male' 32.0 ... 0 7.75 'Q']]


FILLING MISING VALUES

In [8]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[ : ,2].reshape(891,1))
x[ : ,2]=imputer.transform(x[ : ,2].reshape(891,1)).reshape(1,891)

In [9]:
from sklearn.impute import SimpleImputer
imputer1=SimpleImputer(missing_values=np.nan, strategy="most_frequent")
imputer1.fit(x[ : ,6].reshape(891,1))
x[ : ,6]=imputer1.transform(x[ : ,6].reshape(891,1)).reshape(1,891)

ENCODING CATEGORICAL DATA

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[6])],remainder='passthrough')
x=ct.fit_transform(x)

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,4]=le.fit_transform(x[:,4])

In [12]:
print(x[1,:])

[1.0 0.0 0.0 1 0 38.0 1 0 71.2833]


SPLITTING DATASET

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
print(x_train)

[[1.0 0.0 0.0 ... 0 2 15.2458]
 [0.0 0.0 1.0 ... 0 0 10.5]
 [1.0 0.0 0.0 ... 1 1 37.0042]
 ...
 [0.0 1.0 0.0 ... 0 0 7.7333]
 [0.0 0.0 1.0 ... 1 0 17.4]
 [0.0 0.0 1.0 ... 1 1 39.0]]


FEATURE SCALING

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

BUILDING ANN MODEL

In [16]:
ann=tf.keras.models.Sequential()

In [17]:
ann.add(tf.keras.layers.Dense(units=60, activation='relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

COMPILING AND TRAINING ANN MODEL

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
ann.fit(x_train,y_train,batch_size=5, epochs=25)

Epoch 1/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6959 - loss: 0.5984
Epoch 2/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7937 - loss: 0.5004
Epoch 3/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8000 - loss: 0.4356
Epoch 4/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8219 - loss: 0.4233
Epoch 5/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8282 - loss: 0.4204
Epoch 6/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8535 - loss: 0.3532
Epoch 7/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8585 - loss: 0.3680
Epoch 8/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8400 - loss: 0.4077
Epoch 9/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8376 - loss: 0.3934
Epoch 10/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8461 - loss: 0.3852
Epoch 11/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8420 - loss: 0.3949
Epoch 12/25
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

PREDICTING TEST SET RESULTS

In [22]:
y_pred=ann.predict(x_test)
print(y_pred)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.15895867]
 [0.13897438]
 [0.02011126]
 [0.9748664 ]
 [0.58841175]
 [0.27966532]
 [0.9680713 ]
 [0.89675844]
 [0.39510798]
 [0.4033161 ]
 [0.07211728]
 [0.8841737 ]
 [0.05838381]
 [0.9649687 ]
 [0.9698056 ]
 [0.6881994 ]
 [0.12932022]
 [0.46332583]
 [0.12309086]
 [0.80001765]
 [0.14424343]
 [0.9546673 ]
 [0.05838111]
 [0.2783998 ]
 [0.5597644 ]
 [0.968868  ]
 [0.13708167]
 [0.56042945]
 [0.9310882 ]
 [0.55055326]
 [0.09768803]
 [0.8030721 ]
 [0.14133774]
 [0.2671701 ]
 [0.06007173]
 [0.2498903 ]
 [0.08156157]
 [0.09647571]
 [0.09489332]
 [0.07818482]
 [0.07956298]
 [0.23877566]
 [0.15341835]
 [0.01143182]
 [0.98409164]
 [0.13968752]
 [0.13968752]
 [0.9446472 ]
 [0.1294196 ]
 [0.17327775]
 [0.28093433]
 [0.3300969 ]
 [0.9598526 ]
 [0.1265956 ]
 [0.25583747]
 [0.10008963]
 [0.16648093]
 [0.19822094]
 [0.14091544]
 [0.02381133]
 [0.2940136 ]
 [0.46415204]
 [0.97070336]
 [0.2244203 ]
 [0.52557945]
 [0.05232468]
 [0.98203254]
 [0.16594939]
 [0.960813

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[101   9]
 [ 23  46]]
0.8212290502793296
